import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

// ─── Side Menu Styles ────────────────────────────────────────────────────────
export const menuStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
  },
  menu: {
    width: width * 0.62,
    maxWidth: 250,
    maxHeight: height * 0.72,
    backgroundColor: '#16161e',
    borderRadius: 16,
    marginRight: 12,
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,0.1)',
    overflow: 'hidden',
  },
  section: {
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  divider: {
    height: 0.5,
    backgroundColor: 'rgba(255,255,255,0.07)',
    marginHorizontal: 16,
    marginVertical: 2,
  },
  thinDivider: {
    height: 0.5,
    backgroundColor: 'rgba(255,255,255,0.07)',
    marginVertical: 4,
    marginHorizontal: 4,
  },
  navItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 9,
    marginBottom: 2,
  },
  navItemActive: {
    backgroundColor: 'rgba(229,9,20,0.14)',
    borderLeftWidth: 2,
    borderLeftColor: '#E50914',
  },
  navIcon: {
    marginRight: 10,
    width: 20,
    textAlign: 'center',
  },
  navLabel: {
    flex: 1,
    fontSize: 14,
    color: '#888',
    fontWeight: '400',
  },
  navLabelActive: {
    color: '#fff',
    fontWeight: '500',
  },
  subGroup: {
    paddingLeft: 14,
    paddingTop: 2,
    paddingBottom: 2,
  },
  subItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderRadius: 8,
  },
  subLabel: {
    flex: 1,
    fontSize: 13,
    color: '#777',
  },
  badge: {
    backgroundColor: 'rgba(229,9,20,0.2)',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 20,
  },
  badgeText: {
    color: '#E50914',
    fontSize: 11,
    fontWeight: '600',
  },
});

// ─── Main Home Styles ────────────────────────────────────────────────────────
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0f0f13' },

  // Header
  floatingHeader: {
    position: 'absolute',
    top: 0,
    width: '100%',
    zIndex: 99,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingBottom: 12,
    backgroundColor: 'rgba(15,15,19,0.82)',
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(255,255,255,0.06)',
  },
  logo: {
    width: 36,
    height: 36,
    borderRadius: 8,
    marginRight: 12,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderRadius: 10,
    paddingVertical: 9,
    paddingHorizontal: 12,
    alignItems: 'center',
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  searchText: { color: '#E0E0E0', marginLeft: 8, fontSize: 14, fontWeight: '500' },
  menuBtn: {
    marginLeft: 12,
    width: 36,
    height: 36,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,0.08)',
  },

  // Featured
  featuredContainer: { height: height * 0.7, width: '100%' },
  featuredImage:     { width: '100%', height: '100%' },
  gradient:          { position: 'absolute', left: 0, right: 0, bottom: 0, height: 300 },
  featuredContent:   { position: 'absolute', bottom: 0, width: '100%', alignItems: 'center', paddingBottom: 55 },
  featuredCategory:  { color: 'white', fontSize: 13, fontWeight: '600', marginBottom: 18, textShadowColor: 'black', textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 3 },
  featuredActions:   { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-evenly', width: '80%' },
  actionButton:      { alignItems: 'center' },
  actionText:        { color: 'white', fontSize: 12, marginTop: 5, fontWeight: '500' },
  playButton:        { backgroundColor: 'white', flexDirection: 'row', alignItems: 'center', paddingVertical: 10, paddingHorizontal: 24, borderRadius: 5 },
  playButtonText:    { color: 'black', fontSize: 15, fontWeight: 'bold', marginLeft: 6 },
  dotsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: -15,
  },
  thumbnailDotContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    marginHorizontal: 8,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.3)',
    overflow: 'hidden',
  },
  thumbnailDotActive: {
    borderColor: '#fff',
    transform: [{ scale: 1.15 }],
  },
  thumbnailDotImage: {
    width: '100%',
    height: '100%',
  },

  // Lists
  listContainer: { paddingBottom: 50 },
  sectionTitle:  { color: 'white', fontSize: 17, fontWeight: '700', marginLeft: 18, marginTop: 22, marginBottom: 10 },
  row:           { paddingHorizontal: 18 },
  movieCard:     { marginRight: 12 },
  moviePoster:   { width: 108, height: 158, borderRadius: 9 },
  placeholderCard: { backgroundColor: '#222230', justifyContent: 'center', alignItems: 'center', padding: 10 },
  
  // Custom History Card
  historyCard: {
    width: 200,
    height: 100,
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 12,
    marginRight: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  historyPoster: { width: 75, height: '100%' },
  historyInfo: { flex: 1, padding: 10, justifyContent: 'space-between', position: 'relative' },
  historyTitle: { color: 'white', fontSize: 13, fontWeight: '700' },
  historyBadgeRow: { flexDirection: 'row', alignItems: 'center', marginTop: -2 },
  historyBadge: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, marginRight: 6 },
  historyBadgeText: { color: 'white', fontSize: 9, fontWeight: 'bold' },
  historyPlayRow: { flexDirection: 'row', alignItems: 'center', marginTop: 2, marginBottom: 2 },
  historySubtitle: { color: '#bbb', fontSize: 10, marginBottom: 2 },
  historyTime: { color: '#888', fontSize: 10, fontWeight: '500' },
  progressContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 4,
    backgroundColor: '#333',
  },
  progressBar: {
    height: '100%',
    backgroundColor: '#E50914',
  },

  // Custom Watchlist Card
  watchlistCard: {
    marginRight: 14,
    borderRadius: 12,
    overflow: 'hidden',
  },
  watchlistBadge: {
    position: 'absolute',
    top: -2,
    right: 8,
    backgroundColor: '#E50914',
    paddingHorizontal: 4,
    paddingVertical: 6,
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
    zIndex: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
  },

  // Unique Top Comment
  topCommentCard: {
    width: 290,
    backgroundColor: '#1E1925',
    borderRadius: 16,
    padding: 18,
    marginRight: 15,
    borderWidth: 1,
    borderColor: 'rgba(229, 9, 20, 0.2)',
    position: 'relative',
    overflow: 'hidden',
  },
  topQuoteIcon: {
    position: 'absolute',
    top: -10,
    left: 10,
  },
  movieContextBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    backgroundColor: 'rgba(255,255,255,0.04)',
    padding: 6,
    borderRadius: 8,
  },
  contextPoster: {
    width: 24,
    height: 36,
    borderRadius: 4,
    marginRight: 8,
  },
  contextTitle: {
    color: '#FFD700',
    fontSize: 12,
    fontWeight: 'bold',
  },
  contextTime: {
    color: '#888',
    fontSize: 12,
    marginTop: 2,
  },

  // Trailer Modal styles
  trailerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  trailerBox: {
    width: '90%',
    backgroundColor: '#000',
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  trailerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 8,
    paddingHorizontal: 15,
    backgroundColor: '#111',
    alignItems: 'center',
  },
  trailerTitle: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
  },
  topCommentContent: {
    color: '#F0F0F0',
    fontSize: 14,
    fontStyle: 'italic',
    lineHeight: 20,
    minHeight: 60,
    marginTop: 6,
    zIndex: 1,
  },
  topCommentFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.08)',
  },
  topCommentAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    marginRight: 12,
    borderWidth: 1.5,
    borderColor: '#E50914',
  },
  topCommentName: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
  topStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  topStatText: {
    color: '#aaa',
    fontSize: 12,
    marginLeft: 4,
    fontWeight: '600',
  },
  dotSeparator: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#555',
    marginHorizontal: 8,
  },
  topRankBadge: {
    backgroundColor: '#E50914',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  topRankText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '900',
  },

  // Unique Recent Comment (Feed Style)
  recentCommentCard: {
    width: 260,
    backgroundColor: '#151922',
    borderRadius: 16,
    padding: 16,
    marginRight: 15,
    borderLeftWidth: 3,
    borderLeftColor: '#4da6ff',
  },
  recentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  recentAvatarContainer: {
    position: 'relative',
    marginRight: 12,
  },
  recentAvatar: {
    width: 38,
    height: 38,
    borderRadius: 8,
  },
  recentOnlineDot: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 10,
    height: 10,
    backgroundColor: '#00FA9A',
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#151922',
  },
  recentMeta: {
    flex: 1,
    paddingRight: 10,
  },
  recentName: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  recentTime: {
    color: '#4da6ff',
    fontSize: 11,
    marginTop: 2,
    fontWeight: '500',
  },
  recentMovieSide: {
    alignItems: 'flex-end',
    maxWidth: 70,
  },
  recentSidePoster: {
    width: 20,
    height: 30,
    borderRadius: 3,
    marginBottom: 4,
  },
  recentSideTitle: {
    color: '#888',
    fontSize: 9,
    width: 60,
    textAlign: 'right',
  },
  recentContentBubble: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    padding: 12,
    borderRadius: 10,
    borderTopLeftRadius: 2,
  },
  recentContentText: {
    color: '#D1D1D6',
    fontSize: 13,
    lineHeight: 20,
  },
});
