import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#050609',
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: '#050609',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#888888',
    fontSize: 16,
    marginTop: 15,
  },
  backdropWrapper: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 480,
    zIndex: 0,
  },
  backdropImage: {
    width: '100%',
    height: '100%',
    opacity: 0.85,
  },
  backdropPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: '#0e1017',
  },
  backdropOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '100%',
    backgroundColor: 'rgba(5, 6, 9, 0.4)', // General overlay tint
    shadowColor: '#050609',
    elevation: 5,
  },
  scrollContent: {
    paddingBottom: 80,
    zIndex: 10,
  },
  heroSection: {
    paddingHorizontal: 40,
    marginTop: 70,
    height: 310,
    justifyContent: 'flex-end',
    position: 'relative',
    width: '100%',
  },
  heroLeftContent: {
    width: '55%',
    justifyContent: 'flex-end',
  },
  heroTitle: {
    color: '#ffffff',
    fontSize: 36,
    fontWeight: '900',
    marginBottom: 10,
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
    marginBottom: 15,
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 4,
    gap: 4,
  },
  ratingText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  metaText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '600',
  },
  heroDescription: {
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 20,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  heroActions: {
    flexDirection: 'row',
    gap: 15,
  },
  heroButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 22,
    borderRadius: 6,
    gap: 10,
  },
  heroButtonFocused: {
    transform: [{ scale: 1.08 }],
    shadowColor: '#ffffff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  heroButtonText: {
    fontSize: 14,
    fontWeight: '700',
  },
  rowsContainer: {
    marginTop: 40,
  },
  cwRowContainer: {
    marginVertical: 15,
    height: 210,
  },
  cwRowTitle: {
    color: '#e5e5e5',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 5,
    paddingHorizontal: 40,
    letterSpacing: 0.5,
  },
  cwListContent: {
    paddingHorizontal: 40,
    paddingBottom: 30, // Expanded padding bottom for scaling
    paddingTop: 20, // Expanded padding top for scaling
    gap: 20,
  },
  cwCardContainer: {
    width: 220,
    height: 124,
    borderRadius: 8,
    borderWidth: 3,
    borderColor: 'transparent',
    overflow: 'visible',
    backgroundColor: '#161823',
    elevation: 3,
  },
  cwCardContainerFocused: {
    transform: [{ scale: 1.15 }],
    borderWidth: 3,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.45,
    shadowRadius: 10,
    zIndex: 99,
  },
  cwCardInner: {
    width: '100%',
    height: '100%',
    borderRadius: 5,
    overflow: 'hidden',
    position: 'relative',
  },
  cwBackdropImage: {
    width: '100%',
    height: '100%',
  },
  cwPlaceholderCard: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#232635',
  },
  cwPlaceholderText: {
    color: '#ffffff',
    fontSize: 12,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  cwInfoContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    paddingVertical: 5,
    paddingHorizontal: 8,
  },
  cwTitleText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '600',
  },
  cwEpisodeText: {
    color: '#aaaaaa',
    fontSize: 9,
    marginTop: 2,
  },
  cwProgressContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  cwProgressBar: {
    height: '100%',
  },
  heroThumbnailsContainer: {
    position: 'absolute',
    bottom: 20,
    right: 40,
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  heroThumbnail: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    overflow: 'hidden',
    backgroundColor: '#161823',
    elevation: 3,
  },
  heroThumbnailFocused: {
    transform: [{ scale: 1.25 }],
    borderColor: '#ffffff',
    shadowColor: '#ffffff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 5,
  },
  heroThumbnailImage: {
    width: '100%',
    height: '100%',
  },
  heroThumbnailPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: '#232635',
  },
  trailerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  trailerBox: {
    width: '90%',
    maxWidth: 960,
    backgroundColor: '#1a1a1a',
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: '#333333',
  },
  trailerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: '#262626',
    borderBottomWidth: 1,
    borderBottomColor: '#333333',
  },
  trailerTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
    flex: 1,
    marginRight: 20,
  },
  trailerCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  trailerCloseBtnFocused: {
    backgroundColor: '#ffffff',
    borderColor: '#ffffff',
    transform: [{ scale: 1.05 }],
  },
  trailerVideoContainer: {
    width: '100%',
    aspectRatio: 16 / 9,
    backgroundColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  trailerWebView: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  noTrailerContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  noTrailerText: {
    color: '#aaaaaa',
    marginTop: 10,
    fontSize: 16,
    fontWeight: '500',
  },
});
